[package]
name = "hello_pkg_rs"
version = "0.0.1"
authors = ["ubuntu <zhangningbo21@mails.ucas.ac.cn>"]
edition = "2021"

[[bin]]
name = "hello_pkg_rs"
path = "src/main.rs"

[dependencies]
anyhow = {version = "1", features = ["backtrace"]}
rclrs = "*"

# This specific version is compatible with Rust 1.75
backtrace = "=0.3.76"

# uncomment the following section in order to fill in
# further dependencies manually.
# <dependency> = "*" 
